package com.app.api.dtos;


public class DeviceTokenRequestDTO {
    private String fcmToken;

    /**
     * Default constructor for deserialization frameworks.
     * 
     * <p>This no-argument constructor is required for JSON deserialization
     * libraries such as Jackson, Gson, and for Spring's automatic request
     * body binding.
     * 
     * <p>The visibility is package-private to prevent direct instantiation
     * by consumers, while still allowing deserialization frameworks to
     * create instances via reflection.
     */
    DeviceTokenRequestDTO(){

    }

        /**
     * Returns the Firebase Cloud Messaging (FCM) token.
     * 
     * <p>The FCM token is a unique identifier for a specific device
     * application instance. It is generated by the Firebase SDK on the
     * client device and must be sent to the server to enable push
     * notification delivery to that device.
     * 
     * @return The FCM token string, or null if not set
     * @see #setFcmToken(String)
     */
    public String getFcmToken(){
        return fcmToken;
    }

    /**
     * Sets the Firebase Cloud Messaging (FCM) token.
     * 
     * <p>This method is typically used by deserialization frameworks to
     * populate the DTO from the incoming JSON request body.
     * 
     * <p>The token should be a valid FCM registration token format,
     * typically a long alphanumeric string. The server may validate the
     * token format before storing it.
     * 
     * @param fcmToken The FCM token string to be registered
     * @see #getFcmToken()
     * @see <a href="https://firebase.google.com/docs/cloud-messaging/concept-options#registration-token">FCM Registration Tokens</a>
     */
    public void setFcmToken(String fcmToken){
        this.fcmToken = fcmToken;
    }
}
