services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: supa-api-azure

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://parseandco-sqlserver.postgres.database.azure.com:5432/parseandco-database?sslmode=require
      SPRING_DATASOURCE_USERNAME: parseandcosqlserveradmin20261206
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none