-- Flyway migration V1: creates the materialized cluster-membership cache
-- read by the admin dashboard (2.7). Runs once, automatically, on the next
-- application startup after this file is on the classpath — no manual step,
-- unlike the raw script this replaces. Do not edit this file after it has
-- run anywhere: Flyway checksums applied migrations and will refuse to start
-- if the content no longer matches what it recorded. Add a new
-- V2__... file for any further change instead.
 
CREATE TABLE endorsement_cluster_cache (
    cluster_cache_id BIGSERIAL PRIMARY KEY,
 
    -- References location_table(location_id), i.e. the "zone" an
    -- Endorsement is attributed to (Endorsement.zoneid -> Location.locationid).
    location_id       INTEGER   NOT NULL REFERENCES location_table (location_id) ON DELETE CASCADE,
 
    -- References user_table(user_id).
    user_id           INTEGER   NOT NULL REFERENCES user_table (user_id) ON DELETE CASCADE,
 
    -- Community label assigned by the Louvain pass, renumbered to 0..k-1
    -- within each zone/run. Only meaningful alongside location_id: the same
    -- integer in two different zones is not the same community.
    cluster_label     INTEGER   NOT NULL,
 
    -- Sum of endorsement weight to neighbours in the SAME cluster.
    internal_degree   INTEGER   NOT NULL DEFAULT 0,
 
    -- Sum of endorsement weight to ALL neighbours (>= internal_degree).
    -- internal_degree / total_degree is a quick "how tight is this
    -- membership" signal for the admin dashboard.
    total_degree      INTEGER   NOT NULL DEFAULT 0,
 
    -- Identifies which nightly/on-demand run produced this row. All rows
    -- from one run share the same value.
    run_id            UUID      NOT NULL,
 
    computed_at       TIMESTAMP NOT NULL DEFAULT now(),
 
    -- One current membership per (zone, user): the service wipes and
    -- re-inserts a zone's rows on every run rather than accumulating history.
    CONSTRAINT uq_endorsement_cluster_cache_zone_user UNIQUE (location_id, user_id)
);
 
CREATE INDEX idx_endorsement_cluster_cache_zone
    ON endorsement_cluster_cache (location_id);
 
CREATE INDEX idx_endorsement_cluster_cache_zone_cluster
    ON endorsement_cluster_cache (location_id, cluster_label);