// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoq7EmajOyi7-13zPSRML4jIYyxfWPXoc',
    appId: '1:791892980644:web:72d2a6a4b80e0524020731',
    messagingSenderId: '791892980644',
    projectId: 'supa-neighbour',
    authDomain: 'supa-neighbour.firebaseapp.com',
    storageBucket: 'supa-neighbour.firebasestorage.app',
    measurementId: 'G-MWRC2PTKX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTs0Y6cQZBM41VLmIowoq9VQC6ZyM3b3U',
    appId: '1:791892980644:android:d673eb8c631a0110020731',
    messagingSenderId: '791892980644',
    projectId: 'supa-neighbour',
    storageBucket: 'supa-neighbour.firebasestorage.app',
  );
}
