spring.application.name=api
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.security.user.password=disabled
spring.security.user.name=disabled
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.security=TRACE
logging.level.com.app.api=TRACE
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=600000
