package com.app.api.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Builder;
import lombok.Data;

/**
 * Represents a comment on a post in the community forum.
 * Comments can be nested and include timestamps for tracking creation and updates.
 */

@Data
@Builder 
@Entity
@Table(
    name = "event_participants",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "unique_event_participant",
            columnNames = {"event_id", "user_id"}
        )
    }
)
public class EventParticipant {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "participant_id")
    private Integer participantId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Enumerated(EnumType.STRING)
    @Column(name = "participant_status", nullable = false)
    private ParticipantStatus participantStatus = ParticipantStatus.ATTENDING;

    /**
     * Default no-argument constructor required by JPA.
     * <p>
     * Creates an empty {@code EventParticipant} instance. This constructor is
     * primarily used by the persistence provider (e.g., Hibernate) when
     * instantiating entities from the database.
     * </p>
     */
    public EventParticipant() {
        // Required by JPA
    }

    /**
     * Constructs a fully initialized {@code EventParticipant} instance.
     * <p>
     * This constructor allows creating an {@code EventParticipant} with all
     * fields set explicitly. It is useful when building a participant object
     * manually rather than relying on the builder pattern generated by Lombok.
     * </p>
     *
     * @param participantId     the unique identifier of the participant record
     * @param event             the event the user is participating in
     * @param user              the user participating in the event
     * @param participantStatus the current status of the user's participation
     *                          (e.g., attending, declined, maybe)
     */
    public EventParticipant(Integer participantId, Event event, User user, ParticipantStatus participantStatus) {
        this.participantId = participantId;
        this.event = event;
        this.user = user;
        this.participantStatus = participantStatus;
    }
    
}
