package com.app.api.models;

import java.time.LocalDateTime;

import com.google.auto.value.AutoValue.Builder;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Data 
@Builder 
@Entity
@Table(name = "events_table")
public class Event {
    

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "event_id")
    private Integer enventId;

    @ManyToOne()
    @JoinColumn(name = "user_id",nullable=false)
    private User userId;

    @Column(name = "event_title",nullable = false)
    private String eventTitle;

    @Column(name ="description",nullable = false)
    private String description;

    @Column(name = "event_created_at",nullable = false)
    private LocalDateTime eventCreatedAt;

    @Column(name = "event_start_date_time",nullable = false)
    private LocalDateTime eventStartDateTime;

    @Column(name ="event_end_date_time",nullable = false)
    private LocalDateTime eventEndDateTime;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id")
    private Location eventLocation;

    @Column(name = "max_participants")
    private Integer maxParticipants;

    @Column(name = "isLive",nullable = false)
    private boolean isLive = false;

    /**
     * Default no-argument constructor required by JPA.
     * <p>
     * Creates an empty {@code Event} instance. This constructor is primarily
     * used by the persistence provider (e.g., Hibernate) when instantiating
     * entities from the database.
     * </p>
     */
    public Event() {
        // needed for JPA
    }

    /**
     * Constructs a fully initialized {@code Event} instance.
     * <p>
     * This constructor allows creating an {@code Event} with all fields set
     * explicitly. It is useful when building an event object manually rather
     * than relying on the builder pattern generated by Lombok.
     * </p>
     *
     * @param eventId            the unique identifier of the event
     * @param userId             the user associated with the event (owner/creator)
     * @param eventTitle         the title of the event
     * @param description        a detailed description of the event
     * @param eventCreatedAt     the timestamp when the event was created
     * @param eventStartDateTime the start date and time of the event
     * @param eventEndDateTime   the end date and time of the event
     * @param eventLocation      the location where the event takes place
     * @param maxParticipants    the maximum number of participants allowed
     * @param isLive             whether the event is currently live
     */
    public Event(Integer eventId,User userId,String eventTitle,String description,LocalDateTime eventCreatedAt,LocalDateTime eventStartDateTime,LocalDateTime eventEndDateTime,Location eventLocation,Integer maxParticipants,Boolean isLive) {
        this.description=description;
        this.enventId=eventId;
        this.eventCreatedAt=eventEndDateTime;
        this.eventEndDateTime=eventEndDateTime;
        this.eventLocation=eventLocation;
        this.isLive=isLive;
        this.eventStartDateTime=eventStartDateTime;
        this.maxParticipants=maxParticipants;
        this.eventTitle=eventTitle;
    }  
}
